# Generated by Django 3.0.2 on 2020-01-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200130_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
